# Coordinator Configuration

# Log level: LOG_TRACE, LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR
logLevel: LOG_INFO

# Network settings
restIp: 0.0.0.0  # Listen on all interfaces for REST API
coordinatorHost: 192.168.55.100 # Hostname for internal communication (VM IP)
rpcPort: 4000      # Port for RPC communication with workers (default)
restPort: 8081     # Port for REST API (default)

worker:
  # Hostname for the internal worker run by the coordinator
  localWorkerHost: 127.0.0.1

# Logical source definitions
logicalSources:
  - logicalSourceName: "sncb"
    fields:
      - name: timestamp
        type: UINT64
      - name: id
        type: UINT64
      - name: Vbat
        type: FLOAT64
      - name: PCFA_bar
        type: FLOAT64
      - name: PCFF_bar
        type: FLOAT64
      - name: PCF1_bar
        type: FLOAT64
      - name: PCF2_bar
        type: FLOAT64
      - name: T1_bar
        type: FLOAT64
      - name: T2_bar
        type: FLOAT64
      - name: Code1
        type: UINT64
      - name: Code2
        type: UINT64
      - name: speed
        type: FLOAT64
      - name: latitude
        type: FLOAT64
      - name: longitude
        type: FLOAT64

  - logicalSourceName: "highriskArea"
    fields:
      - name: timestamp
        type: UINT64
      - name: latitude
        type: FLOAT64
      - name: longitude
        type: FLOAT64

  - logicalSourceName: "weather"
    fields:
      - name: timestamp
        type: UINT64
      - name: temperature
        type: FLOAT64
      - name: precipitation
        type: FLOAT64
      - name: rain
        type: FLOAT64
      - name: snowfall
        type: FLOAT64
      - name: snowfall_height
        type: FLOAT64
      - name: freezing_level_height
        type: FLOAT64
      - name: weather_code
        type: UINT64
      - name: wind_speed
        type: FLOAT64
      - name: wind_speed_80m
        type: FLOAT64
      - name: wind_direction_10m
        type: FLOAT64
      - name: wind_direction_80m
        type: FLOAT64
      - name: wind_gusts_10m
        type: FLOAT64
      - name: gps_lat
        type: FLOAT64
      - name: gps_lon
        type: FLOAT64

  - logicalSourceName: "nrok5"
    fields:
      - name: id
        type: UINT64
      - name: timestamp
        type: UINT64
      - name: PCFA_bar
        type: FLOAT64
      - name: PCFF_bar
        type: FLOAT64
      - name: PCF1_bar
        type: FLOAT64
      - name: PCF2_bar
        type: FLOAT64
      - name: T1_bar
        type: FLOAT64
      - name: T2_bar
        type: FLOAT64
      - name: Code1
        type: UINT64
      - name: Code2
        type: UINT64
      - name: time
        type: UINT64

  - logicalSourceName: "nrok5Oneday"
    fields:
      - name: id
        type: UINT64
      - name: timestamp
        type: UINT64
      - name: PCFA_bar
        type: FLOAT64
      - name: PCFF_bar
        type: FLOAT64
      - name: PCF1_bar
        type: FLOAT64
      - name: PCF2_bar
        type: FLOAT64
      - name: T1_bar
        type: FLOAT64
      - name: T2_bar
        type: FLOAT64
      - name: Code1
        type: UINT64
      - name: Code2
        type: UINT64