# ~~~ Configurations for the NES E2E Benchmark ~~~

benchmarkName: SNCBQuery1GeospatialBenchmark
outputFile: sncb_query1_results.csv

# Parameter that are changed per run with comma separated list
numberOfWorkerThreads: 1,2
numberOfSources: 1

# engine configuration parameter - REDUCED for VM
numberOfBuffersInGlobalBufferManager: 1024
numberOfBuffersPerPipeline: 128
numberOfBuffersInSourceLocalBufferPool: 128
bufferSizeInBytes: 4096

logicalSources:
  - name: sncb
    type: Default

# configure data source - REDUCED for VM
numberOfPreAllocatedBuffer: 1000
dataGenerator: Default
dataProvider: Internal
dataProviderMode: ZeroCopy

query: 'Query::from("sncb").filter((Attribute("id") != 0 || Attribute("payload") != 0)).window(TumblingWindow::of(EventTime(Attribute("timestamp")), Seconds(30))).apply(Sum(Attribute("value"))).sink(NullOutputSinkDescriptor::create());'

gatheringValues: 10000

# benchmark internal parameter - REDUCED for VM
numberOfBuffersToProduce: 5000000
scalability: scale-up
logLevel: LOG_INFO
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 2
numberOfMeasurementsToCollect: 3