# ~~~ SNCB Query4 E2E Benchmark Configuration ~~~

benchmarkName: SNCBQuery4Benchmark
outputFile: sncb_query4_e2e_results.csv

# Parameter that are changed per run with comma separated list
numberOfWorkerThreads: 1,2
numberOfSources: 2

# engine configuration parameter - VM optimized
numberOfBuffersInGlobalBufferManager: 1024
numberOfBuffersPerPipeline: 128
numberOfBuffersInSourceLocalBufferPool: 128
bufferSizeInBytes: 4096

logicalSources:
  - name: sncb
    type: SNCB
    csvPath: /media/psf/Home/Parallels/nebulaQueryAPI/data/selected_columns_df.csv
    minSpeed: 0
    maxSpeed: 120
    minLongitude: 4.0    # Belgium longitude range
    maxLongitude: 6.5
    minLatitude: 49.5    # Belgium latitude range  
    maxLatitude: 51.5

# configure data source - VM optimized
numberOfPreAllocatedBuffer: 1000
dataProvider: Internal
dataProviderMode: ZeroCopy

# Query4: Map attributes for both streams
querySet:
  - query: 'Query::from("sncb").map(Attribute("t_timestamp") = Attribute("timestamp")).map(Attribute("t_lat") = Attribute("latitude")).map(Attribute("t_lon") = Attribute("longitude")).map(Attribute("t_speed") = Attribute("speed")).sink(FileSinkDescriptor::create("sncb_query4_train_output.csv", "CSV_FORMAT", "APPEND"));'

gatheringValues: 10000

# benchmark internal parameter - VM optimized
numberOfBuffersToProduce: 1000000
scalability: scale-up
logLevel: LOG_INFO
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 2
numberOfMeasurementsToCollect: 5