# ~~~ SNCB Query6 E2E Benchmark Configuration ~~~

benchmarkName: SNCBQuery6Benchmark
outputFile: sncb_query6_e2e_results.csv

# Parameter that are changed per run with comma separated list
numberOfWorkerThreads: 1,2
numberOfSources: 1

# engine configuration parameter - optimized for complex query
numberOfBuffersInGlobalBufferManager: 2048
numberOfBuffersPerPipeline: 256
numberOfBuffersInSourceLocalBufferPool: 256
bufferSizeInBytes: 4096

logicalSources:
  - name: sncb
    type: SNCB
    csvPath: /media/psf/Home/Parallels/nebulaQueryAPI/data/selected_columns_df_milliseconds.csv
    minSpeed: 0
    maxSpeed: 120
    minLongitude: 4.0    # Belgium longitude range
    maxLongitude: 6.5
    minLatitude: 49.5    # Belgium latitude range  
    maxLatitude: 51.5

# configure data source - reduced for complex processing
numberOfPreAllocatedBuffer: 500
dataProvider: Internal
dataProviderMode: ZeroCopy

# Query6: Sliding window with min/max aggregations and variation calculations (optimized)
query: 'Query::from("sncb").window(SlidingWindow::of(EventTime(Attribute("timestamp", BasicType::UINT64)), Seconds(10), Seconds(5))).apply(Min(Attribute("PCFA_bar"))->as(Attribute("PCFA_min_value")), Max(Attribute("PCFA_bar"))->as(Attribute("PCFA_max_value")), Min(Attribute("PCFF_bar"))->as(Attribute("PCFF_min_value")), Max(Attribute("PCFF_bar"))->as(Attribute("PCFF_max_value"))).map(Attribute("wStart") = Attribute("start")).map(Attribute("wEnd") = Attribute("end")).map(Attribute("variationPCFA") = Attribute("PCFA_max_value") - Attribute("PCFA_min_value")).map(Attribute("variationPCFF") = Attribute("PCFF_max_value") - Attribute("PCFF_min_value")).filter(Attribute("variationPCFA") > 0.4 && Attribute("variationPCFF") <= 0.1).project(Attribute("wStart"), Attribute("wEnd"), Attribute("variationPCFA"), Attribute("variationPCFF")).sink(FileSinkDescriptor::create("sncb_query6_e2e_output.csv", "CSV_FORMAT", "APPEND"));'

gatheringValues: 500

# benchmark internal parameter - reduced for complex query
numberOfBuffersToProduce: 1000
scalability: scale-up
logLevel: LOG_DEBUG
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 5
numberOfMeasurementsToCollect: 10