# Worker Configuration

# Log level: LOG_TRACE, LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR
logLevel: LOG_INFO

# Network settings
coordinatorHost: 127.0.0.1  # IP of the coordinator in Parallels VM
localWorkerHost: 127.0.0.1    # IP of the worker (NVIDIA device)
rpcPort: 4001                    # Port for RPC communication with coordinator
dataPort: 4002                   # Port for data transfer

# Physical source definitions
physicalSources:
  - logicalSourceName: sncb  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: gpsCSV # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /home/emma/nebulaQueryAPI/data/selected_columns_df.csv # Use absolute path
      skipHeader: true
      delimiter: ","
      numberOfBuffersToProduce: 0 # 0 means infinite
      numberOfTuplesToProducePerBuffer: 36 
      gatheringInterval: 1000 # milliseconds

  - logicalSourceName: highriskArea  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: highriskAreaCSV # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /home/emma/nebulaQueryAPI/data/high_risk_areas_ordered_unix.csv # Use absolute path
      skipHeader: true
      delimiter: ","


  - logicalSourceName: weather  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: weatherCSV # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /home/emma/nebulaQueryAPI/data/weatherwithsynccoordinates.csv # Use absolute path
      skipHeader: true
      delimiter: ","
      numberOfBuffersToProduce: 0 # 0 means infinite
      numberOfTuplesToProducePerBuffer: 0
      gatheringInterval: 0 # milliseconds
  
  - logicalSourceName: nrok5  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: nrokCSV # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /home/emma/nebulaQueryAPI/data/nrok5-VTC1030-NES.csv # Use absolute path
      skipHeader: true
      delimiter: ","
      numberOfBuffersToProduce: 0 # 0 means infinite
      numberOfTuplesToProducePerBuffer: 0
      gatheringInterval: 0 # milliseconds

  - logicalSourceName: nrok5Oneday  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: nrok5Oneday # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /home/emma/nebulaQueryAPI/data/nrok5-oneWorktime_ForNES.csv # Use absolute path
      skipHeader: true
      delimiter: ","
      numberOfBuffersToProduce: 0 # 0 means infinite
      numberOfTuplesToProducePerBuffer: 0
      gatheringInterval: 0 # milliseconds

workerId: 2

# Configure the query compiler to use the SLICING window strategy
queryCompiler:
  windowingStrategy: SLICING