# Worker Configuration

# Log level: LOG_TRACE, LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR
logLevel: LOG_INFO

# Network settings
coordinatorHost: 127.0.0.1  # Hostname/IP of the coordinator (use localhost)
localWorkerHost: 127.0.0.1  # Unique hostname for this worker (use localhost)
rpcPort: 4001             # Port for RPC communication with coordinator (default is 4000, must be unique per worker)
dataPort: 4002            # Port for data transfer (default is 4001, must be unique per worker)

# Physical source definitions
physicalSources:
  - logicalSourceName: sncb  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: gpsCSV # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /media/psf/Home/Parallels/nebulaQueryAPI/data/selected_columns_df.csv # Use absolute path
      skipHeader: true
      delimiter: ","
      numberOfBuffersToProduce: 0 # 0 means infinite
      numberOfTuplesToProducePerBuffer: 36 # Reduced to fit buffer size (40 * 96 bytes < 4096 bytes)
      gatheringInterval: 1000 # milliseconds

  - logicalSourceName: highriskArea  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: highriskAreaCSV # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /media/psf/Home/Parallels/nebulaQueryAPI/data/high_risk_areas_ordered_unix.csv # Use absolute path
      skipHeader: true
      delimiter: ","


  - logicalSourceName: weather  # Link to the logical source defined in coordinator.yaml
    physicalSourceName: weatherCSV # Unique name for this physical source
    type: CSV_SOURCE          # Type of the source
    configuration:
      filePath: /media/psf/Home/Parallels/nebulaQueryAPI/data/weatherwithsynccoordinates.csv # Use absolute path
      skipHeader: true
      delimiter: ","


workerId: 2